### ISSUE TITLE
Mathtools commands not working

### ISSUE THREAD

**Issue by myca-sheaf** [wei2912/obsidian-latex#14]
With Mathjax now at version 3.2, it would be nice if we could include mathtools commands in our macro definitions (with mathtools, i would be able to use nearly all of my usual LaTeX macros in Obsidian). However, it appears not to be working. For instance, including `\DeclarePairedDelimiters{\p}{(}{)}` in the preamble.sty file does not allow `\p` to be used in Obsidian. But one can check that writing `\DeclarePairedDelimiters{\p}{(}{)} \p{a}` straight into Obsidian *does* compile as intended.

I'm using Obsidian v0.12.15.
Thanks!

**Comment by xldenis** [comment]
Hmm, I'll take a look. thanks for the report

**Comment by wei2912** [comment]
@austinsid Are you still able to replicate this issue? On Obsidian v1.1.9 this seems to work fine for me:

![image](https://user-images.githubusercontent.com/2070423/209464171-6461aba3-f173-4c31-a8d2-e6898f0bdc5b.png)
