### ISSUE TITLE
give it a better id

### ISSUE THREAD

**Issue by ksdavidc** [wei2912/obsidian-latex#26]
I kept getting a console error from plugin 'obsidian-latex' ...took me a long time to figure out it was this plugin. Is it possible to change the id to something more identifiable?

**Comment by wei2912** [comment]
@ksdavidc Sorry for the late reply! I'd like to change the id of this plugin, but doing so could break automatic updates for existing users. Given that this plugin is largely stable and unlikely to change much (unless MathJax integration becomes more flexible), I prefer to avoid any such breaking changes.
