### ISSUE TITLE
newcommands not rendering correctly

### ISSUE THREAD

**Issue by jaythad13** [wei2912/obsidian-latex#31]
I'm trying to use this plugin with Obsidian 1.4.14 on macOS, but the commands don't seem to work. Weirdly, it doesn't work when I look at the example file on GitHub either: the example file has "\typing" in red.
I'm not sure if this is an issue just on my end or the plugin has just stopped working as a whole

This is what's in my preamble.sty file
\newcommand{\bb}[1]{\mathbb{#1}}
\newcommand{\bvec}[1]{\mathbf{#1}}
\newcommand{\pardx}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\ddx}[2]{\frac{d #1}{d #2}}

And this is what it displays after typing "For a function $f : \bb{R} \to \bb{R}$"

<img width="673" alt="Screenshot 2023-09-27 at 2 44 32 PM" src="https://github.com/wei2912/obsidian-latex/assets/90142166/326a53ef-8e99-4d09-9931-de5080827571">

This is what the example Markdown file looks like to me

<img width="734" alt="Screenshot 2023-09-27 at 2 48 39 PM" src="https://github.com/wei2912/obsidian-latex/assets/90142166/780d25b7-d6cc-4892-adb7-76b4b8cabcfc">

**Comment by wei2912** [comment]
@jaythad13 Just to confirm, does this work for you now? You would need to reload Obsidian before you can use the new commands.

**Comment by jaythad13** [comment]
Yeah it's working fine now.
